params:
  - params.yaml
stages:
  label_data_extract:
    cmd: python pipelines/label_training_data.py
      "inputs/label_data/${label_data_extract.basename}.tsv" 
      ${label_data_extract.freq}
      "outputs/label_data/${label_data_extract.basename}.csv"
    deps:
      - "pipelines/label_training_data.py"
      - "inputs/label_data/${label_data_extract.basename}.tsv" 