params:
- params.yaml
- dvclive/params.yaml
stages:
  label_data_extract:
    cmd: python pipelines/extract_data_to_label.py 
      "inputs/label_data/${label_data_extract.basename}.tsv" 
      ${label_data_extract.freq} 
      "inputs/labeled_data/${label_data_extract.pre_labels}.csv" 
      "outputs/label_data/${label_data_extract.basename}.csv" 
      "outputs/${label_data_extract.counts_outname}.csv"
    deps:
    - pipelines/extract_data_to_label.py
    - inputs/label_data/${label_data_extract.basename}.tsv
    - inputs/labeled_data/${label_data_extract.pre_labels}.csv
    - wikilacra/stream.py
    outs:
    - outputs/label_data/${label_data_extract.basename}.csv
    - outputs/${label_data_extract.counts_outname}.csv
  labeled_data_transform:
    cmd: python pipelines/labeled_data_transform.py 
      "${labeled_data_transform.start_dt}" 
      ${labeled_data_transform.rolling_avg_hrs} 
      "inputs/labeled_data/${labeled_data_transform.labeled_basename}.csv" 
      "outputs/labeled_transformed/${labeled_data_transform.outname}.csv"
    deps:
    - pipelines/labeled_data_transform.py
    - inputs/labeled_data/${labeled_data_transform.labeled_basename}.csv
    outs:
    - outputs/labeled_transformed/${labeled_data_transform.outname}.csv
  features:
    cmd: python pipelines/engineer-features.py 
      ${labeled_data_transform.rolling_avg_hrs} 
      "inputs/label_data/${label_data_extract.basename}.tsv" 
      "outputs/labeled_transformed/${labeled_data_transform.outname}.csv" 
      "outputs/${label_data_extract.counts_outname}.csv" 
      "outputs/labeled_transformed/${features.outname}.csv"
    deps:
    - inputs/label_data/${label_data_extract.basename}.tsv
    - pipelines/engineer-features.py
    - outputs/labeled_transformed/${labeled_data_transform.outname}.csv
    - outputs/${label_data_extract.counts_outname}.csv
    - wikilacra/features.py
    outs:
    - outputs/labeled_transformed/${features.outname}.csv
  train-RF:
    cmd: python pipelines/RF.py 
      "outputs/labeled_transformed/${features.outname}.csv" 
      ${train-RF.metric_name} ${train-RF.random_state} ${train-RF.shuffle} 
      ${train-RF.n_jobs} ${train-RF.max_depths_gen} "${train-RF.max_depths}" 
      ${train-RF.n_estimators_gen} "${train-RF.n_estimators}" 
      ${train-RF.test_prop} ${train-RF.K_fold_cv}
    deps:
    - pipelines/RF.py
    - outputs/labeled_transformed/${features.outname}.csv
    - wikilacra/scoring.py
    - wikilacra/data.py
    outs:
    - dvclive/
plots:
- dvclive/plots/metrics:
    x: step
metrics:
- dvclive/metrics.json
