params:
- params.yaml
- dvclive/params.yaml
- dvclive/RF/params.yaml
- dvclive/XGBT/params.yaml
- dvclive/LinSVC/params.yaml
stages:
  label_data_extract:
    cmd: python pipelines/extract_data_to_label.py 
      "inputs/label_data/${label_data_extract.basename}.tsv" 
      ${label_data_extract.freq} 
      "inputs/labeled_data/${label_data_extract.pre_labels}.csv" 
      "outputs/label_data/${label_data_extract.basename}.csv" 
      "outputs/${label_data_extract.counts_outname}.csv"
    deps:
    - pipelines/extract_data_to_label.py
    - inputs/label_data/${label_data_extract.basename}.tsv
    - inputs/labeled_data/${label_data_extract.pre_labels}.csv
    - wikilacra/stream.py
    outs:
    - outputs/label_data/${label_data_extract.basename}.csv
    - outputs/${label_data_extract.counts_outname}.csv
  features:
    cmd: python pipelines/engineer-features.py ${features.rolling_avg_hrs} 
      ${features.intra_pd} ${features.intra_win} 
      "inputs/label_data/${features.dump_basename}.tsv" 
      "inputs/labeled_data/${features.labeled_basename}.csv" 
      "outputs/labeled_engineered/" "${features.basename}" 
      "${features.start_dt}" "${features.end_dt}"
    deps:
    - inputs/label_data/${features.dump_basename}.tsv
    - pipelines/engineer-features.py
    - wikilacra/__init__.py
    - wikilacra/features.py
    - wikilacra/stream.py
    - inputs/labeled_data/${features.labeled_basename}.csv
    outs:
    - outputs/labeled_engineered/${features.basename}.csv
    - outputs/labeled_engineered/${features.basename}_exog_cols.txt
    - outputs/labeled_engineered/${features.basename}_endog_cols.txt
  train-RF:
    cmd: python pipelines/RF.py "outputs/labeled_engineered/" 
      "${train-RF.input_name}" ${train-RF.metric_name} ${train-RF.random_state} 
      ${train-RF.n_jobs} ${train-RF.max_depths_gen} "${train-RF.max_depths}" 
      ${train-RF.n_estimators_gen} "${train-RF.n_estimators}" 
      ${train-RF.test_prop} ${train-RF.CV_type} ${train-RF.N_fold_cv}
    deps:
    - pipelines/RF.py
    - outputs/labeled_engineered/${train-RF.input_name}.csv
    - wikilacra/scoring.py
    - wikilacra/data.py
    outs:
    - dvclive/RF/metrics.json
    - dvclive/RF/params.yaml
    - dvclive/RF/plots/images/FeatureImportances.png
    - dvclive/RF/plots/images/ConfusionMatrixDisplay.png
  train-XGBT:
    cmd: python pipelines/XGBT.py "outputs/labeled_engineered/" 
      "${train-XGBT.input_name}" ${train-XGBT.metric_name} 
      ${train-XGBT.random_state} ${train-XGBT.n_jobs} 
      ${train-XGBT.max_depths_gen} "${train-XGBT.max_depths}" 
      ${train-XGBT.test_prop} ${train-XGBT.CV_type} ${train-XGBT.N_fold_cv}
    deps:
    - pipelines/XGBT.py
    - outputs/labeled_engineered/${train-XGBT.input_name}.csv
    - wikilacra/scoring.py
    - wikilacra/data.py
    outs:
    - dvclive/XGBT/metrics.json
    - dvclive/XGBT/params.yaml
    - dvclive/XGBT/plots/images/FeatureImportances.png
    - dvclive/XGBT/plots/images/ConfusionMatrixDisplay.png
  train-LinSVC:
    cmd: python pipelines/LinearSVC.py "outputs/labeled_engineered/" 
      "${train-LinSVC.input_name}" ${train-LinSVC.metric_name} 
      ${train-LinSVC.random_state} ${train-LinSVC.n_jobs} 
      ${train-LinSVC.test_prop} ${train-LinSVC.CV_type} 
      ${train-LinSVC.N_fold_cv} ${train-LinSVC.scale_type} ${train-LinSVC.C_gen}
      "${train-LinSVC.C}" "${train-LinSVC.loss}"
    deps:
    - pipelines/LinearSVC.py
    - outputs/labeled_engineered/${train-LinSVC.input_name}.csv
    - wikilacra/scoring.py
    - wikilacra/data.py
    - wikilacra/scaling.py
    outs:
    - dvclive/LinSVC/metrics.json
    - dvclive/LinSVC/params.yaml
    - dvclive/LinSVC/plots/images/ConfusionMatrixDisplay.png
  train-NN:
    cmd: python pipelines/NN.py "outputs/labeled_engineered/" 
      "${train-NN.input_name}" ${train-NN.metric_name} ${train-NN.random_state} 
      ${train-NN.n_jobs} ${train-NN.val_prop} ${train-NN.test_prop} 
      ${train-NN.scale_type} ${train-NN.lr} ${train-NN.dropout} 
      ${train-NN.N_hidden} ${train-NN.size_hidden} ${train-NN.activation} 
      ${train-NN.epochs} ${train-NN.pos_weight}
    deps:
    - pipelines/NN.py
    - outputs/labeled_engineered/${train-NN.input_name}.csv
    - wikilacra/scoring.py
    - wikilacra/data.py
    - wikilacra/scaling.py
    outs:
    - dvclive/NN/metrics.json
    - dvclive/NN/plots/images/ConfusionMatrixDisplay.png
    - dvclive/NN/plots/metrics/val
    - dvclive/NN/plots/metrics/train
plots:
- dvclive/NN/plots/metrics:
    x: step
- dvclive/NN/plots/images
- dvclive/RF/plots/images
- dvclive/XGBT/plots/images
- dvclive/LinSVC/plots/images
metrics:
- dvclive/NN/metrics.json
- dvclive/RF/metrics.json
- dvclive/XGBT/metrics.json
- dvclive/LinSVC/metrics.json
artifacts:
  RF-model:
    path: outputs/models/RF-model.pkl
  XGBT-model:
    path: outputs/models/XGBT-model.pkl
  LinSVC-model:
    path: outputs/models/LinSVC-model.pkl
  NN-model:
    path: outputs/models/NN-model.pt
  NN-model-state:
    path: outputs/models/NN-model-state.pt
