params:
- params.yaml
- dvclive/params.yaml
stages:
  label_data_extract:
    cmd: python pipelines/extract_data_to_label.py 
      "inputs/label_data/${label_data_extract.basename}.tsv" 
      ${label_data_extract.freq} 
      "inputs/labeled_data/${label_data_extract.pre_labels}.csv" 
      "outputs/label_data/${label_data_extract.basename}.csv" 
      "outputs/${label_data_extract.counts_outname}.csv"
    deps:
    - pipelines/extract_data_to_label.py
    - inputs/label_data/${label_data_extract.basename}.tsv
    - inputs/labeled_data/${label_data_extract.pre_labels}.csv
    - wikilacra/stream.py
    outs:
    - outputs/label_data/${label_data_extract.basename}.csv
    - outputs/${label_data_extract.counts_outname}.csv
  features:
    cmd: python pipelines/engineer-features.py 
      ${features.rolling_avg_hrs} 
      ${features.intra_pd} ${features.intra_win}
      "inputs/label_data/${features.dump_basename}.tsv" 
      "inputs/labeled_data/${features.labeled_basename}.csv" 
      "outputs/labeled_engineered/${features.outname}.csv"
      "${features.start_dt}" "${features.end_dt}"
    deps:
    - inputs/label_data/${features.dump_basename}.tsv
    - pipelines/engineer-features.py
    - wikilacra/
    - inputs/labeled_data/${features.labeled_basename}.csv
    outs:
    - outputs/labeled_engineered/${features.outname}.csv
  train-RF:
    cmd: python pipelines/RF.py 
      "outputs/labeled_engineered/${train-RF.input_name}.csv" 
      ${train-RF.metric_name} ${train-RF.random_state} ${train-RF.n_jobs} 
      ${train-RF.max_depths_gen} "${train-RF.max_depths}" 
      ${train-RF.n_estimators_gen} "${train-RF.n_estimators}" 
      ${train-RF.test_prop} ${train-RF.K_fold_cv}
    deps:
    - pipelines/RF.py
    - outputs/labeled_engineered/${train-RF.input_name}.csv
    - wikilacra/scoring.py
    - wikilacra/data.py
    outs:
    - dvclive/
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
- dvclive/plots/images
