params:
  - params.yaml
stages:
  label_data_extract:
    cmd: python pipelines/label_training_data.py
      "inputs/label_data/${label_data_extract.basename}.tsv" 
      ${label_data_extract.freq}
      "outputs/label_data/${label_data_extract.basename}.csv"
    deps:
      - "pipelines/label_training_data.py"
      - "inputs/label_data/${label_data_extract.basename}.tsv" 
    outs:
      - "outputs/label_data/${label_data_extract.basename}.csv"
  labeled_data_transform:
    cmd: python pipelines/labeled_data_transform.py 
      ${labeled_data_transform.rolling_avg_hrs} 
      "inputs/label_data/${labeled_data_transform.revisions_basename}.tsv"
      "inputs/labeled_data/${labeled_data_transform.labeled_basename}.csv" 
      "${labeled_data_transform.start_dt}"
      "${labeled_data_transform.freq}"
      "outputs/labeled_transformed/${labeled_data_transform.outname}.csv"
    deps:
      - "pipelines/labeled_data_transform.py"
      - "inputs/label_data/${labeled_data_transform.revisions_basename}.tsv"
      - "inputs/labeled_data/${labeled_data_transform.labeled_basename}.csv" 
    outs:
    - "outputs/labeled_transformed/${labeled_data_transform.outname}.csv"
  train-RF:
    cmd: python pipelines/clean.py
    deps:
    outs: